name:                fqt
version:             0.1.0.0
github:              "DevdudeSami/fqt"
license:             BSD3
author:              "Youssef Moawad"
maintainer:          "y.moawad.1@research.gla.ac.uk"
copyright:           "(c) Youssef Moawad"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DevdudeSami/fqt>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4
- split
- text
- MissingH
- directory
- parsec
- pretty
- haskeline
- mtl
- process
- integer-logarithms

library:
  source-dirs:
  - src
  - src/core
  - src/compiler
  - src/circuits
  - src/circuits/math
  - src/testing  

executables:
  fqt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - fqt

tests:
  fqt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - fqt
